name: CI/CD - Data Upload Service

on:
  # Trigger build/test on pushes to any branch
  push:
    branches:
      - '**'
  
  # Trigger build/test for pull requests targeting main
  pull_request:
    branches:
      - main

  # Allow manual triggering for deployment or rollbacks
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (namespace)'
        required: true
        default: 'analytics'
        type: choice
        options:
          - analytics
          - staging
          - production
      image_tag:
        description: 'OPTIONAL: Specific image tag to deploy (for rollback)'
        required: false
        type: string

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/data-upload-service
  SERVICE_NAME: dataUploadService      # Must match the key in your Helm values.yaml
  HELM_RELEASE_NAME: data-upload-service # The deployment name in Kubernetes

jobs:
  # ==================================
  # CI STAGE: Build & Test
  # ==================================
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter and security audit
        run: |
          npm run lint || true
          npm audit --audit-level high || true

      - name: Run tests
        run: npm test

      - name: Set build variables
        id: vars
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        # Only log in if we are actually going to push an image
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        # Only build and push on a merge to main or a manual trigger
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.image_tag }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ==================================
  # CD STAGE: Deploy to Kubernetes
  # ==================================
  deploy-to-kubernetes:
    runs-on: self
